
services:
    orbitale.api.originChecker:
        class: Orbitale\Bundle\ApiBundle\Services\OriginChecker
        arguments:
            allowedOrigins: %orbitale_api.allowed_origins%

    orbitale.api.listener:
        class: Orbitale\Bundle\ApiBundle\Listeners\JsonResponseListener
        arguments:
            kernelEnvironment: %kernel.debug%
        tags:
            - { name: kernel.event_subscriber }
