
services:
    pierstoval.api.originChecker:
        class: Pierstoval\Bundle\ApiBundle\Services\OriginChecker
        arguments:
            allowedOrigins: %pierstoval_api.allowed_origins%
            authentication: %pierstoval_api.authentication%
            kernelEnvironment: %kernel.environment%

    pierstoval.api.listener:
        class: Pierstoval\Bundle\ApiBundle\Listeners\JsonResponseListener
        arguments:
            kernelEnvironment: %kernel.environment%
        tags:
            - { name: kernel.event_subscriber }
