
services:

    orbitale.api.json_response.listener:
        class: Orbitale\Bundle\ApiBundle\Listeners\JsonResponseListener
        arguments:
            kernelEnvironment: "%kernel.debug%"
        tags:
            - { name: kernel.event_subscriber }
