# Based on EasyAdminBundle's travis file
# @link https://github.com/javiereguiluz/EasyAdminBundle

language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.app/cache

env:
  global:
    - deps="no"
    - COMPOSER_FLAGS=""
    - SYMFONY_VERSION=""
    - SYMFONY_DEPRECATIONS_HELPER="strict"
    - ENABLE_CODE_COVERAGE="false"

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: SYMFONY_VERSION="3.0.*"

    - php: 5.6
      env: SYMFONY_VERSION="2.8.*"

    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-lowest"
      env: SYMFONY_VERSION="2.8.*"

    - php: hhvm
      env: SYMFONY_VERSION="2.8.*"

    - php: 7.0
      env: SYMFONY_VERSION="3.0.*"
      env: ENABLE_CODE_COVERAGE="true"

    - php: 5.6

  allow_failures:
    - php: hhvm
    - env: ENABLE_CODE_COVERAGE="true"

before_install:
  - composer selfupdate
  - if [[ "$SYMFONY_VERSION" != "" ]]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [[ "$ENABLE_CODE_COVERAGE" != "true" && "$TRAVIS_PHP_VERSION" != hhvm ]]; then phpenv config-rm xdebug.ini; fi;

install:
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
  - if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then composer require --dev satooshi/php-coveralls; fi

script:
  - if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then phpunit --coverage-text --coverage-clover build/logs/clover.xml; else phpunit; fi;

after_success: |
    if [[ "$ENABLE_CODE_COVERAGE" == "true" ]]; then php vendor/bin/coveralls -v --config .coveralls.yml; fi;

notifications:
    email: alex@orbitale.io
