orbitale_api_delete:
    defaults:
        _controller: 'OrbitaleApiBundle:Api:delete'
    methods: DELETE
    path: /{serviceName}/{entity}/{id}
    requirements:
        serviceName: \w+
        entity:      \w+
        id:          \w+
