orbitale_api_get_collection:
    defaults:
        _controller: OrbitaleApiBundle:Api:getCollection
    methods: GET
    path: /{serviceName}/{entity}
    requirements:
        serviceName: \w+
        entity:      \w+
