orbitale_api_delete:
    defaults:
        _controller: 'OrbitaleApiBundle:Api:post'
    methods: POST
    path: /{serviceName}/{entity}
    requirements:
        serviceName: \w+
        entity:      \w+
