orbitale_api_index:
    defaults:
        _controller: OrbitaleApiBundle:Api:index
    methods: GET
    path: /services

orbitale_api_service_info:
    defaults:
        _controller: OrbitaleApiBundle:Api:serviceInfo
    methods: GET
    path: /services/{serviceName}
    requirements:
        serviceName: \w+
